#!/usr/bin/env python3
"""harvest-noesis.py — pick-and-choose harvester (PRIVATE, stealth).

Greps Will's OWN repos for code that DIRECTLY serves the Noesis roadmap — the
portable mechanism primitives (Shapley/Myerson, commit-reveal, Bradley-Terry,
core/nucleolus, CKB/Cell, eigenvector value-flow, slashing, provenance). Writes a
deduped pick-list to NOESIS-HARVEST.md for Will to triage. INDIRECT/tangential
terms are deliberately excluded ("we'll do indirect stuff later").

Pure stdlib (no ripgrep dep). Cron-callable. Idempotent: rewrites the harvest file.
"""
import os
import re
import pathlib

HOME = pathlib.Path.home()
REPOS = [HOME / "vibeswap", HOME / "jarvis-monorepo", HOME / "JARVIS"]
OUT = HOME / "jarvis-private" / "NOESIS-HARVEST.md"

SCAN_EXT = {".sol", ".py", ".rs"}  # CODE only — .md is discussion, not portable code
SKIP_DIRS = {".git", "node_modules", "out", "target", "cache", "dist", "build",
             "_obsidian-view", "lib", "__pycache__", "broadcast", "artifacts"}
SKIP_PREFIX = ("out-",)  # foundry profile out dirs

# DIRECT roadmap buckets → keyword regexes. Curated: each maps to a real Noesis
# roadmap item (CONTINUE.md NEXT increments / WHITEPAPER). Indirect terms omitted.
BUCKETS = {
    "value aggregation (Myerson / Shapley)": r"\b(Myerson|Shapley(?:Distributor)?|graph[-_ ]?restricted)\b",
    "value elicitation (Bradley-Terry / reward model)": r"\b(Bradley[-_ ]?Terry|reward[-_ ]?model|RLHF|pairwise)\b",
    "value estimation (Data-Shapley / sampling)": r"\b(Data[-_ ]?Shapley|monte[-_ ]?carlo|permutation[-_ ]?sampl)\b",
    "value-flow (eigenvector / EigenTrust)": r"\b(eigen(vector|trust)|pagerank)\b",
    "commit-reveal provenance": r"\b(commit[-_ ]?reveal|CommitReveal|reveal\s*phase|hash\(.*secret)\b",
    "value rule (temporal-novelty)": r"\b(temporal[-_ ]?novelty|novelty\s*score|coverage\s*proxy)\b",
    "consensus stability (core / nucleolus)": r"\b(nucleolus|\bcore\b\s*(stability|imputation)|imputation)\b",
    "slashing / dispute": r"\b(slash(ing|ed)?|dispute\s*window|invalid\s*reveal)\b",
    "substrate (CKB / Cell / RISC-V)": r"\b(ckb[-_ ]?vm|cell\s*model|RISC[-_ ]?V|type[-_ ]?script|lock[-_ ]?script|state[-_ ]?rent)\b",
    "ownership fold (UTXO / transfer-log)": r"\b(UTXO|transfer[-_ ]?fold|ownership\s*fold|transfer\s*log)\b",
}

def scan():
    hits = {b: {} for b in BUCKETS}  # bucket -> {relpath: (lineno, line)}
    compiled = {b: re.compile(p, re.IGNORECASE) for b, p in BUCKETS.items()}
    for repo in REPOS:
        if not repo.is_dir():
            continue
        for root, dirs, files in os.walk(repo):
            dirs[:] = [d for d in dirs if d not in SKIP_DIRS
                       and not d.startswith(SKIP_PREFIX)]
            for fn in files:
                if pathlib.Path(fn).suffix.lower() not in SCAN_EXT:
                    continue
                p = pathlib.Path(root) / fn
                try:
                    lines = p.read_text(encoding="utf-8", errors="ignore").splitlines()
                except Exception:
                    continue
                rel = str(p).replace(str(HOME), "~").replace("\\", "/")
                for i, line in enumerate(lines, 1):
                    for b, rx in compiled.items():
                        if rel in hits[b]:
                            continue  # one hit per file per bucket (dedupe)
                        if rx.search(line):
                            hits[b][rel] = (i, line.strip()[:120])
    return hits

def write(hits):
    total = sum(len(v) for v in hits.values())
    out = ["# Noesis Harvest — pick-and-choose (PRIVATE, stealth)", "",
           "> Auto-generated by `scripts/harvest-noesis.py`. Code in Will's own repos that",
           "> **directly** serves the Noesis roadmap (portable mechanism primitives).",
           "> Triage: tick what to port/reuse; ignore the rest. Indirect candidates deferred.",
           f"> {total} candidate file(s) across {len([r for r in REPOS if r.is_dir()])} repos.", ""]
    for b in BUCKETS:
        files = hits[b]
        if not files:
            continue
        out.append(f"## {b}  ({len(files)})")
        for rel, (ln, snip) in sorted(files.items()):
            out.append(f"- [ ] `{rel}:{ln}` — {snip}")
        out.append("")
    OUT.write_text("\n".join(out), encoding="utf-8")
    return total

if __name__ == "__main__":
    n = write(scan())
    print(f"harvest-noesis: {n} candidates -> {OUT}")
